import './globals.css';
import { Inter } from 'next/font/google';
import { Metadata } from 'next';
import clsx from 'clsx';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  viewport: 'width=device-width, initial-scale=1',
  icons: ['/favicon.ico'],
  themeColor: '#ffffff'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'flex min-h-screen flex-col items-center  p-24')}>
        <nav className="flex w-full gap-4">
          <button>
            <Link href="/">Home</Link>
          </button>
          <button>
            <Link href="/about">About</Link>
          </button>
          <button>
            <Link href="/detail/123">detail</Link>
          </button>
        </nav>
        {children}
      </body>
    </html>
  );
}
